---
title: Bandits
---

```{r}
library(tidyverse)

theme_set(theme_minimal())

run_simulation <- function (params, output) {
  system(paste("./target/release/bandit", params, ">", output))
  
  bandit_data <- read_csv(output, show_col_types = FALSE) |>
    mutate(run = row_number())
  
  probs <- bandit_data |>
    pivot_longer(cols = starts_with("bandit_prob_"), names_to = "bandit", values_to = "p") |>
    ggplot(aes(x = run, y = p, color = bandit)) +
    geom_line(linewidth = 0.75) +
    labs(
      title = "Learned Probabilities",
      x = "Run Number",
      y = "Probability of Success"
    )

  regret <- bandit_data |>
    ggplot(aes(x = run, y = regret)) +
    geom_line(linewidth = 0.75) + 
    labs(
      title = "Regret over Time",
      x = "Run Number",
      y = "Regret"
    )
  
  print(probs)
  print(regret)
  
  return(bandit_data)
}
```


```{r}
run_simulation("0.22 0.21 0.215 0.2175 0.19 0.36 0.215 0.2 0.15 0.22 5000 decay 0.75 0.005", "bandits.csv")
```

```{r}
probs <- "0.20 0.21 0.215 0.2175 0.19 0.23 0.215 0.2 0.15 0.22"
samples <- "50000"

system(paste("./target/release/bandit", probs, samples, " oracle > oracle.csv"))
system(paste("./target/release/bandit", probs, samples, " constant > constant.csv"))
system(paste("./target/release/bandit", probs, samples, " naive > naive.csv"))
system(paste("./target/release/bandit", probs, samples, " epsilon 0.1 > epsilon.csv"))
system(paste("./target/release/bandit", probs, samples, " decay 0.75 0.01 > decay.csv"))
system(paste("./target/release/bandit", probs, samples, " thompson > thompson.csv"))
system(paste("./target/release/bandit", probs, samples, " cruz > cruz.csv"))
```

```{r}
bandit_oracle <- read_csv("oracle.csv", show_col_types = FALSE) |>
  mutate(run = row_number()) |>
  rename_with(~ paste("oracle_", ., sep = ""), !matches("run"))

bandit_const <- read_csv("constant.csv", show_col_types = FALSE) |>
  mutate(run = row_number()) |>
  rename_with(~ paste("constant_", ., sep = ""), !matches("run"))

bandit_naive <- read_csv("naive.csv", show_col_types = FALSE) |>
  mutate(run = row_number()) |>
  rename_with(~ paste("naive_", ., sep = ""), !matches("run"))

bandit_epsilon <- read_csv("epsilon.csv", show_col_types = FALSE) |>
  mutate(run = row_number()) |>
  rename_with(~ paste("epsilon_", ., sep = ""), !matches("run"))

bandit_decay <- read_csv("decay.csv", show_col_types = FALSE) |>
  mutate(run = row_number()) |>
  rename_with(~ paste("decay_", ., sep = ""), !matches("run"))

bandit_thompson <- read_csv("thompson.csv", show_col_types = FALSE) |>
  mutate(run = row_number()) |>
  rename_with(~ paste("thompson_", ., sep = ""), !matches("run"))

bandit_cruz <- read_csv("cruz.csv", show_col_types = FALSE) |>
  mutate(run = row_number()) |>
  rename_with(~ paste("cruz_", ., sep = ""), !matches("run"))

run <- join_by(run == run)
bandits <- bandit_oracle |>
  inner_join(bandit_const, run) |>
  inner_join(bandit_naive, run) |>
  inner_join(bandit_epsilon, run) |>
  inner_join(bandit_decay, run) |>
  inner_join(bandit_thompson, run) |>
  inner_join(bandit_cruz, run)

bandits |> select(run, matches("regret")) |>
  pivot_longer(cols = matches(("regret")), names_pattern = "(.*?)_regret", names_to = "strategy", values_to = "regret") |>
  ggplot(aes(x = run, y = regret, color = strategy)) +
  geom_line(linewidth = 0.75) +
  scale_x_continuous(label = scales::comma) +
  scale_y_continuous(label = scales::comma) +
  labs(
    title = "Regret Race",
    x = "Impressions",
    y = "Lost Clicks",
    color = "Strategy"
  )
```















